package com.ares.xq.testgreemdao.dao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ares.xq.testgreemdao.dao.entity.StudentBean;
import com.ares.xq.testgreemdao.dao.entity.TecherBean;

import com.ares.xq.testgreemdao.dao.dao.StudentBeanDao;
import com.ares.xq.testgreemdao.dao.dao.TecherBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentBeanDaoConfig;
    private final DaoConfig techerBeanDaoConfig;

    private final StudentBeanDao studentBeanDao;
    private final TecherBeanDao techerBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentBeanDaoConfig = daoConfigMap.get(StudentBeanDao.class).clone();
        studentBeanDaoConfig.initIdentityScope(type);

        techerBeanDaoConfig = daoConfigMap.get(TecherBeanDao.class).clone();
        techerBeanDaoConfig.initIdentityScope(type);

        studentBeanDao = new StudentBeanDao(studentBeanDaoConfig, this);
        techerBeanDao = new TecherBeanDao(techerBeanDaoConfig, this);

        registerDao(StudentBean.class, studentBeanDao);
        registerDao(TecherBean.class, techerBeanDao);
    }
    
    public void clear() {
        studentBeanDaoConfig.clearIdentityScope();
        techerBeanDaoConfig.clearIdentityScope();
    }

    public StudentBeanDao getStudentBeanDao() {
        return studentBeanDao;
    }

    public TecherBeanDao getTecherBeanDao() {
        return techerBeanDao;
    }

}
